config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'rooms#index'
  post 'rooms/index'
  post 'guests/index'
  post 'bookings/index'
  post 'staffs/index'
  post 'controls/index'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rooms.rb
class Rooms < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def index

	end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
	def index

	end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
	def index

	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

	def index
		response = HTTParty.get('URI')
	end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
	def index

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<!-- BOOKING -->
<div class="col-md-5" id="rooomcontent">
	<td>
	    <table><tr><td>
	    	<input type="text" name="search" placeholder="GUESTS: ">
	    </td><td id="widtd">
	    </td><td>
	    	<%= button_to "ADD", onclick="myFunction()", :id => "add-edit-btn", :method => :get %>
	    </td><td>
	    &nbsp; &nbsp; &nbsp; &nbsp;
	    </td><td>
	    	<%= button_to "EDIT", root_path, :id => "add-edit-btn", :method => :get %>
	    </td></td></table>
	</td>


	<br>
	<br>
		<table class="table table-striped table-inverse StandardTable" id="table-status">
		  <thead>
		    <tr>
		      <th>GUEST #</th>
		      <th>PHONE NO.</th>
		      <th>EMAIL</th>
		      <th>DOB</th>
		      <th>ADDRESS</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<tr> &nbsp; </tr>
		    <tr id="trs">
		      <td id="guestname">LOLITA ENRIQUEZ</td>
		      <td>0912345678</td>
		      <td>lolita@en.com</td>
		      <td>01/01/01</td>
		      <td>ARDS HOME</td>
		    </tr>
		    <tr id="trs">
		      <td id="guestname">LOLITA ENRIQUEZ</td>
		      <td>0912345678</td>
		      <td>lolita@en.com</td>
		      <td>01/01/01</td>
		      <td>ARDS HOME</td>
		    </tr>
		    <tr id="trs">
		      <td id="guestname">LOLITA ENRIQUEZ</td>
		      <td>0912345678</td>
		      <td>lolita@en.com</td>
		      <td>01/01/01</td>
		      <td>ARDS HOME</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		  </tbody>
		</table>
</div>

app/views/guests/index.html.erb
<!-- GUEST -->
<div class="col-md-5" id="rooomcontent">
	<td>
	    <table><tr><td>
	    	<input type="text" name="search" placeholder="GUESTS: ">
	    </td><td id="widtd">
	    </td><td>
	    	<%= button_to "ADD", root_path, :id => "add-edit-btn", :method => :get %>
	    </td><td>
	    &nbsp; &nbsp; &nbsp; &nbsp;
	    </td><td>
	    	<%= button_to "EDIT", root_path, :id => "add-edit-btn", :method => :get %>
	    </td></td></table>
	</td>


	<br>
	<br>
		<table class="table table-striped table-inverse StandardTable" id="table-status">
		  <thead>
		    <tr>
		      <th>GUEST #</th>
		      <th>ROOM NO.</th>
		      <th>CHECK-IN</th>
		      <th>CHECK-OUT</th>
		      <th>STATUS OF PAYMENT</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<tr> &nbsp; </tr>
		    <tr id="trs">
		      <td id="guestname">LOLITA ENRIQUEZ</td>
		      <td>1001</td>
		      <td>12:00 01/01/01</td>
		      <td>12:00 01/01/01</td>
		      <td>UNPAID</td>
		    </tr>
		    <tr id="trs">
		      <td id="guestname">LOLITA ENRIQUEZ</td>
		      <td>1001</td>
		      <td>12:00 01/01/01</td>
		      <td>12:00 01/01/01</td>
		      <td>UNPAID</td>
		    </tr>
		    <tr id="trs">
		      <td id="guestname">LOLITA ENRIQUEZ</td>
		      <td>1001</td>
		      <td>12:00 01/01/01</td>
		      <td>12:00 01/01/01</td>
		      <td>UNPAID</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		  </tbody>
		</table>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="row">
      <div class="col-md-3" id="header">
        <div class="navbar-header navbar-custom">
          <%= link_to "Admin", root_path, class: "navbar-brand", id: "head"%>
        </div>
      </div>

      <div class="col-md-1">
        <div class="navbar-header navbar-custom">
          <%= button_to "ROOMS", rooms_index_path, id: "field" %>
        </div>
      </div>

      <div class="col-md-1">
        <div class="navbar-header navbar-custom">
          <%= button_to "GUESTS", guests_index_path, id: "field" %>
        </div>
      </div>

      <div class="col-md-1">
        <div class="navbar-header navbar-custom">
          <%= button_to "STAFF", staffs_index_path, id: "field" %>
        </div>
      </div>

      <div class="col-md-1">
        <div class="navbar-header navbar-custom">
          <%= button_to "CONTROLS", controls_index_path, id: "field-control" %>
        </div>
      </div>
      <div class="col-md-1">
        <div class="navbar-header navbar-custom">
          <%= button_to "BOOKING", bookings_index_path, id: "field-booking" %>
        </div>
      </div>

      <div class="col-md-1">
      &nbsp;
      </div>

      <div class="col-md-1">
        <div class="navbar-header navbar-custom">
          <%= button_to "LOG OUT", rooms_index_path, id: "field-logout" %>
        </div>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-md-3 sidebar">
	<div id="dash">
		<label id="ldash">DASHBOARD</label>
	</div>

	<ul class="nav nav-sidebar">
	    <li class="sidebar_overview">
	    	<%= link_to "CC10", "https://www.facebook.com/chiara.cruz.7", target: "_blank", rel: "alternate" %>
	    </li>
		</ul>

		<ul class="nav nav-sidebar">
      <li class="sidebar_company_info">
      	<%= link_to "Hayabusa", "http://www.mobilelegends.com/hero/detail-21", target: "_blank", rel: "alternate" %>
      </li>
	</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigation'%>
    <%= render 'layouts/sidebar'%>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<!-- ROOMS -->
<section class="col-md-5" id="rooomcontent">
	<br>
	<br>
	<div align="center">
		 <input type="text" name="search" placeholder="FLOOR: ">
	</div>
	<br>
	<br>
		<table class="table table-striped table-inverse StandardTable" id="table-status">
		  <thead>
		    <tr>
		      <th>ROOM #</th>
		      <th>GUESTS</th>
		      <th>STATUS</th>
		      <th>ELAPSED TIME</th>
		      <th>STAFF IN-CHARGE</th>
		    </tr>
		  </thead>
		  <tbody>
		  	<tr> &nbsp; </tr>
		    <tr id="trs">
		      <td id="room">2019</td>
		      <td>RICHARD PARKER</td>
		      <td>DND</td>
		      <td>23:10</td>
		      <td>LOLITA ENRIQUEZ</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">2019</td>
		      <td>RICHARD PARKER</td>
		      <td>DND</td>
		      <td>23:10</td>
		      <td>LOLITA ENRIQUEZ</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		    <tr id="trs">
		      <td id="room">&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		      <td>&nbsp;</td>
		    </tr>
		  </tbody>
		</table>
</section>